# Generated by Django 5.0.7 on 2024-07-15 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uploaded_by',
            new_name='created_by',
        ),
    ]
