# Generated by Django 5.0.7 on 2024-07-15 20:36

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_uploaded_by_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=product.models.video_upload_path),
        ),
    ]
